swagger: "2.0"
info:
  version: "1.0.0"
  title: "AuthRequestSchema"
  description: "API for managing events"
  host : "http://localhost:3001/"
basePath: "/"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

swagger: "2.0"
info:
  version: "1.0.0"
  title: "AuthRequestSchema"
  description: "API for managing events"
schemes:
  - "http"
host: "localhost:3001"
basePath: "/"

consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /randomEvents:
    get:
      description: "Get random events"
      responses:
        "200":
          description: "Success"
          schema:
            type: "object"
        "500":
          description: "Internal Server Error"
          schema:
            type: "object"
      tags:
        - "Events"
  /getEventData:
    get:
      description: "Get event data"
      responses:
        "200":
          description: "Success"
          schema:
            type: "object"
        "500":
          description: "Internal Server Error"
          schema:
            type: "object"
      tags:
        - "Events"
  /getEventsWithLocation:
    get:
      description: "Get events with location"
      responses:
        "200":
          description: "Success"
          schema:
            type: "object"
        "500":
          description: "Internal Server Error"
          schema:
            type: "object"
      tags:
        - "Events"
  /eventAds/{city}:
    get:
      description: "Get event ads by city"
      parameters:
        - name: "city"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "Success"
          schema:
            type: "object"
        "500":
          description: "Internal Server Error"
          schema:
            type: "object"
      tags:
        - "Events"
  /randomEvents:
    get:
      description: "Get random events"
      responses:
        "200":
          description: "Success"
          schema:
            type: "object"
        "500":
          description: "Internal Server Error"
          schema:
            type: "object"
      tags:
        - "Events"
  http://localhost:3001/getEventData:
    get:
      description: "Get event data"
      responses:
        "200":
          description: "Success"
          schema:
            type: "object"
        "500":
          description: "Internal Server Error"
          schema:
            type: "object"
      tags:
        - "Events"
  http://localhost:3001/getEventsWithLocation:
    get:
      description: "Get events with location"
      responses:
        "200":
          description: "Success"
          schema:
            type: "object"
        "500":
          description: "Internal Server Error"
          schema:
            type: "object"
      tags:
        - "Events"
  http://localhost:3001/eventAds/{city}:
    get:
      description: "Get event ads by city"
      parameters:
        - name: "city"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "Success"
          schema:
            type: "object"
        "500":
          description: "Internal Server Error"
          schema:
            type: "object"
      tags:
        - "Events"
servers:
  - url: "http://localhost:{port}"
    variables:
      port:
        default: "3001"